export * from './sample-4.0-xml/inline';
export * from './sample-4.0-xml/wrapper';
export * from './sample-4.1-xml/wrapper';
export * from './sample-4.1-xml/inline';
export * from './sample-4.2-xml/inline';
export * from './sample-4.2-xml/wrapper';
export * from './sample-3.0-xml/wrapper';
export * from './sample-3.0-xml/inline';
export * from './sample-2.0-xml/inline';
